name: crypto
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - fire==0.6.0
      - frozenlist==1.4.1
      - idna==3.6
      - joblib==1.3.2
      - multidict==6.0.5
      - numpy==1.26.4
      - pandas==2.2.1
      - pyarrow==15.0.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - six==1.16.0
      - termcolor==2.4.0
      - tzdata==2024.1
      - xmltodict==0.13.0
      - yarl==1.9.4